# Assignment 1

## Name: UWAILA EKHATOR

### Collaborators: TAPIWA MWILA AND QIJIA LIU


# Notes

Submit your homework by uploading it in the directory with your name. Please mention in this file the names of any students with whom you collaborated. If you didn't collaborate with anyone, mark your collaborators as "None." 
Remember, your goal is to communicate. Full credit will be given only to correct solutions which are described clearly. Convoluted and obtuse descriptions will receive low marks. 
To complete your homework, you may ONLY consult the following material: 
1.	lecture slides
2.	course notes you or others took during lecture.
3.	the required text (CLRS)
4.	websites that may clarify the concepts covered in the material but do not in any way provide complete solutions to the problems.

Deadline

Please provide an answer to the following questions: 

# Question 1 (10 pts)

Create a script that: 
1. loads the iris dataset.
2. scales the independent features.
3. computes the correlation coefficients and co-variance among all pairs of independent features.
4. computes the PCA and shows the principal components (their coefficients) 
5. computes the correlation coefficient between each original feature and the new features generated by the PCA 


#### 1. Loading the iris dataset:

In [14]:
import numpy as np
import pandas as pd
iris_data=pd.read_csv("iris.csv")
iris_data.columns = ['sepal length', 'sepal width', 'petal length', 'petal width', 'class']

In [15]:
iris_data

sepal length  sepal width  petal length  petal width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

#### 2. Scaling the independent features:

This would be done using sklearn preprocessing, which basically computes the mean and standard deviation of each feature across the dataset. Then, it subtracts the mean from each feature value and divides by the standard deviation. This centers the data around zero and scales it to have a standard deviation of 1.

In [16]:
from sklearn import preprocessing
iris_data_scaled = iris_data.drop(columns=['class'])
iris_data_scaled = preprocessing.scale(iris_data_scaled)
iris_data_scaled = pd.DataFrame(iris_data_scaled,columns=['sepal length', 'sepal width', 'petal length', 'petal width'])

In [17]:
iris_data_scaled

sepal length  sepal width  petal length  petal width
0       -0.900681     1.032057     -1.341272    -1.312977
1       -1.143017    -0.124958     -1.341272    -1.312977
2       -1.385353     0.337848     -1.398138    -1.312977
3       -1.506521     0.106445     -1.284407    -1.312977
4       -1.021849     1.263460     -1.341272    -1.312977
..            ...          ...           ...          ...
145      1.038005    -0.124958      0.819624     1.447956
146      0.553333    -1.281972      0.705893     0.922064
147      0.795669    -0.124958      0.819624     1.053537
148      0.432165     0.800654      0.933356     1.447956
149      0.068662    -0.124958      0.762759     0.790591

[150 rows x 4 columns]

In [18]:
iris_data_scaled.describe(include='all')

sepal length   sepal width  petal length   petal width
count  1.500000e+02  1.500000e+02  1.500000e+02  1.500000e+02
mean  -4.736952e-16 -6.631732e-16  3.315866e-16 -2.842171e-16
std    1.003350e+00  1.003350e+00  1.003350e+00  1.003350e+00
min   -1.870024e+00 -2.438987e+00 -1.568735e+00 -1.444450e+00
25%   -9.006812e-01 -5.877635e-01 -1.227541e+00 -1.181504e+00
50%   -5.250608e-02 -1.249576e-01  3.362659e-01  1.332259e-01
75%    6.745011e-01  5.692513e-01  7.627586e-01  7.905908e-01
max    2.492019e+00  3.114684e+00  1.786341e+00  1.710902e+00

#### 3. Compute the correlation coefficients and co-variance among all pairs of independent features.

In [19]:
#Compute correlation coefficient
correlation_coef = iris_data_scaled.corr()

#Compute covariance
covariance = iris_data_scaled.cov()

In [20]:
#Print correlation Coefficients
print("Correlation Coefficients:")
print(correlation_coef)

Correlation Coefficients:
              sepal length  sepal width  petal length  petal width
sepal length      1.000000    -0.109369      0.871754     0.817954
sepal width      -0.109369     1.000000     -0.420516    -0.356544
petal length      0.871754    -0.420516      1.000000     0.962757
petal width       0.817954    -0.356544      0.962757     1.000000


The correlation coefficient measures the strength and direction of a linear relationship between 2 variables, it ranges between -1 and 1.<br>
A correlation coefficient value of 1 indicates a perfect positive linear relationship, <br>
-1 indicates a perfect negative linear relationship, and <br>
0 indicates no linear relationship


In [21]:
# Print covariance
print("\nCovariance:")
print(covariance)


Covariance:
              sepal length  sepal width  petal length  petal width
sepal length      1.006711    -0.110103      0.877605     0.823443
sepal width      -0.110103     1.006711     -0.423338    -0.358937
petal length      0.877605    -0.423338      1.006711     0.969219
petal width       0.823443    -0.358937      0.969219     1.006711


Covariance measures the degree to which 2 variables move together.

#### 4. Compute the PCA and shows the principal components (their coefficients)

In [22]:
from sklearn.decomposition import PCA
pc = PCA(n_components=4, random_state=20)
X_PCA = pc.fit(iris_data_scaled)

In [23]:
d=iris_data.values
X=d[:,0:4]
y=d[:,4]

print("Number of Principal Components:", pc.n_components)
print()
print("Principal Components (Eigen Vectors):\n", pc.components_)
print()
print("Explained Variance (Eigen Values):", pc.explained_variance_)
print()
print("Sum of explained Variance for Principal Components:", np.sum(pc.explained_variance_))
print()
print("Variance of Original Features:", X[:,0].var(),X[:,1].var(),X[:,2].var(),X[:,3].var())
print()
print("Sum of Variance for Original Features:", X[:,0].var()+X[:,1].var()+X[:,2].var()+X[:,3].var())
print()
print("Variance Ratio:", pc.explained_variance_ratio_)

Number of Principal Components: 4

Principal Components (Eigen Vectors):
 [[ 0.52237162 -0.26335492  0.58125401  0.56561105]
 [ 0.37231836  0.92555649  0.02109478  0.06541577]
 [-0.72101681  0.24203288  0.14089226  0.6338014 ]
 [-0.26199559  0.12413481  0.80115427 -0.52354627]]

Explained Variance (Eigen Values): [2.93035378 0.92740362 0.14834223 0.02074601]

Sum of explained Variance for Principal Components: 4.026845637583891

Variance of Original Features: 0.6811222222222222 0.1867506666666667 3.0924248888888854 0.5785315555555559

Sum of Variance for Original Features: 4.5388293333333305

Variance Ratio: [0.72770452 0.23030523 0.03683832 0.00515193]


#### 5. Compute the correlation coefficient between each original feature and the new features generated by the PCA

In [24]:
pcTransformed = pc.transform(iris_data_scaled)
pcadata = pd.DataFrame(pcTransformed, columns = ["PC1", "PC2", "PC3", "PC4"])
corr_coef = pd.concat([pcadata, iris_data_scaled], axis=1).corr().iloc[:4, 4:]
print("Correlation coefficients between each original feature and new features generated by the PCA:")
print()
corr_coef

Correlation coefficients between each original feature and new features generated by the PCA:



sepal length  sepal width  petal length  petal width
PC1      0.891224    -0.449313      0.991684     0.964996
PC2      0.357352     0.888351      0.020247     0.062786
PC3     -0.276774     0.092908      0.054084     0.243295
PC4     -0.037610     0.017820      0.115009    -0.075157

# Question 2 (5 pts + (5 pts Extra))

1. What you can observe by comparing the results in Question 1 sections 4 and 5?
2. Can you define any property indicated by these results?
3. If there is any property are you able to formally prove it? i.e., make a formall math proof (5 extra pts)

#### 1. What you can observe by comparing the results in Question 1 sections 4 and 5?

- The positive and negattive signs are in the same position for the principal components
- The features that have the highest coefficient in any Eigen vector also has the highest correlation with that principal component, followed by the feature with the next highest coefficient in that Eigen vector, in that order.
- In section 5, PC1 has the highest correlation with all original features because it explains most, followed by PC2 and PC4 has the smallest

#### 2. Can you define any property indicated by these results?

The correlation between $x_i, y_k$ is: <br><br>
$\rho(x_i,y_k) = \frac{Cov(x_i,y_k)}{Var(x_i)Var(y_k)} $ <br>
where $x_i$ is the original feature or variable and $y_k$ is the principal component<br>


#### 3.If there is any property are you able to formally prove it? i.e., make a formal math proof (5 extra pts)

The correlation between $x_i, y_k$ is: <br><br>
$\rho(x_i,y_k) = \frac{Cov(x_i,y_k)}{Var(x_i)Var(y_k)} $ <br>
$ = \frac{\lambda_k a_{ik}}{\sqrt{\sigma_{ii}}\sqrt{\lambda_k}}$<br>
$ = a_{ik}(\frac{\lambda_k}{\sigma_{ii}})^\frac{1}{2} $ <br>

where $x_i$ is the original feature or variable and $y_k$ is the principal component<br>
$\lambda_k$: This represents the eigenvalue corresponding to the k-th principal component <br>
$\sigma_{ii}$: This represents the variance of the original feature $x_i$.


# Question 3 (10 pts)

1) Write code in pure python (Numpy and Scipy are allowed, SciKit implementation for the decision tree is not allowed) to implement a decision tree. In input, you should provide the independent features and the dependent feature (the class) separately.
The independent features can be binary, categorical, or numerical. You can use a vector that describes the type of each independent feature (binary, categorical, or numerical). The class or the target is binary or categorical (use an id to implement each class)
Please implement the Gini index and the entropy gain ratio. You can use the code developed in class.

2) Create a toy example to run and test your code (please show the result).



The gini index formula is $ 1 - \sum_{i=0}^{c-1} p_{i}(t) ^2$

In [25]:
def gini_index(y):
    # Count the occurrences of each class label
    values, counts = np.unique(y, return_counts=True)
    # Calculate the probability of each class label
    class_probs = counts / len(y)
    # Calculate the Gini index
    gini = 1 - np.sum(np.square(class_probs))
    return gini

The information gain formular is $\Delta = I(parent) - I(children)$ <br>
where $I(parent) =  1 - \sum_{i=0}^{c-1} p_{i}(t) ^2$ <br>
and $I(children) = \sum_{j=1}^{k} \frac{N(V_{j})}{N} I(v_{j})$<br>
$I(children)$ in this case can be written as $(\frac{N_{left}}{N_{total}} * Gini(left)) + (\frac{N_{right}}{N_{total}} * Gini(right))$

In [27]:
def information_gain_gini(y, left_indices, right_indices):
    # Calculate the Gini index before the split (I(parent))
    gini_parent = gini_index(y)
    
    # Calculate the Gini index after the split (I(children))
    gini_left = gini_index(y[left_indices])
    gini_right = gini_index(y[right_indices])
    
    # Calculate the weighted average Gini index after the split
    weighted_gini_children = (len(left_indices) / len(y)) * gini_left + (len(right_indices) / len(y)) * gini_right
    
    # Calculate the information gain using Gini index (Delta = I(parent) - I(children))
    gain = gini_parent - weighted_gini_children
    return gain

The entropy formula is $ - \sum_{i=0}^{c-1} p_{i}(t)log_{2}p_{i}t$

In [28]:
def entropy(y):
    # Count the occurrences of each class label
    values, counts = np.unique(y, return_counts=True)
    # Calculate the probability of each class label
    class_probs = counts / len(y)
    # Calculate the entropy
    entropy = -np.sum(class_probs * np.log2(class_probs + 1e-10))  # Adding a small value to prevent log(0)
    return entropy

Gain ratio = $\frac{Information gain}{Split Info}$<br>
Where split info = $-\sum_{i=1}^{k} \frac{N(V_{i})}{N} log_{2} \frac{N(V_{i})}{N} $ <br> 
which can be written as=
$-(\frac{N_{left}}{N_{total}} log_{2} \frac{N_{left}}{N_{total}} ) + (\frac{N_{right}}{N_{total}} log_{2} \frac{N_{right}}{N_{total}} )$

In [29]:
def gain_ratio(y, left_indices, right_indices):
    # Calculate the information gain
    gain = information_gain_gini(y, left_indices, right_indices)
    # Calculate the split information
    split_info = -((len(left_indices) / len(y)) * np.log2(len(left_indices) / len(y) + 1e-10) +
                   (len(right_indices) / len(y)) * np.log2(len(right_indices) / len(y) + 1e-10))
    # Calculate the gain ratio
    gain_ratio = gain / split_info if split_info != 0 else 0  # Avoid division by zero
    return gain_ratio

In [30]:
def scoref(X, y, f, criterion):
    if criterion == 'gini':
        # Calculate the Gini index for the split
        gini_left = gini_index(y[X[:, f] == 0])
        gini_right = gini_index(y[X[:, f] == 1])
        weighted_gini = (len(X[X[:, f] == 0]) / len(y)) * gini_left + (len(X[X[:, f] == 1]) / len(y)) * gini_right
        score = weighted_gini
    elif criterion == 'information_gain':
        # Calculate the information gain for the split
        left_indices = np.where(X[:, f] == 0)[0]
        right_indices = np.where(X[:, f] == 1)[0]
        score = information_gain_gini(y, left_indices, right_indices)
    elif criterion == 'entropy_gain_ratio':
        # Calculate the gain ratio for the split
        left_indices = np.where(X[:, f] == 0)[0]
        right_indices = np.where(X[:, f] == 1)[0]
        score = gain_ratio(y, left_indices, right_indices)
    else:
        raise ValueError("Invalid criterion. Supported values are 'gini', 'information_gain', and 'entropy_gain_ratio'.")
    return score

In [31]:
def isSplittable(y):
    #checks if y has more than 1 unique element, if it has just 1 unique element there is no point splitting further
    return len(set([a for a in y]))!=1

def bestClass(y):#this counts and returns the class label that occurs most frequently in the input list 'y'
    h=set([a for a in y])
    best=-1 #stores count of most frequent class
    valueBest=-1 #stores the most frequent class label
    for f in h:
        count=np.sum(y==f)#counts the number of occurrences in current class label 'f' in the input list 'y'
        if count>=best:
            best=count
            valueBest=f
    return valueBest



def createTree(X, y, criterion='gini'):  # Add a default criterion parameter
    if X.shape[0] > 1 and isSplittable(y):
        best = -19000000
        bestindex = -1
        for i in range(X.shape[1]):
            if len(set([h for h in X[:, i]])) > 1:
                if criterion == 'gini':
                    score = scoref(X, y, i, criterion)  # Use scoref with Gini index
                elif criterion == 'information_gain':
                    left_indices = np.where(X[:, i] == 0)[0]
                    right_indices = np.where(X[:, i] == 1)[0]
                    score = information_gain_gini(y, left_indices, right_indices)  # Calculate information gain using Gini index
                elif criterion == 'entropy_gain_ratio':
                    left_indices = np.where(X[:, i] == 0)[0]
                    right_indices = np.where(X[:, i] == 1)[0]
                    score = gain_ratio(y, left_indices, right_indices)  # Calculate gain ratio using Gini index
                else:
                    raise ValueError("Invalid criterion. Supported values are 'gini', 'information_gain', and 'entropy_gain_ratio'.")
                
                if best <= score:
                    best = score
                    bestindex = i

        if bestindex == -1:
            return ('l', bestClass(y))
        else:
            cr = createTree(X[X[:, bestindex] == 0], y[X[:, bestindex] == 0], criterion)  # Recur with the selected criterion
            cl = createTree(X[X[:, bestindex] == 1], y[X[:, bestindex] == 1], criterion)  # Recur with the selected criterion
            return ('n', (bestindex, cr, cl))
    else:
        return ('l', bestClass(y))


#### Toy Example

In [32]:
X = np.array([[0, 1], [1, 0], [1, 1], [0, 0]])
y = np.array([0, 1, 1, 0])
print(X)
print(y)

[[0 1]
 [1 0]
 [1 1]
 [0 0]]
[0 1 1 0]


In [33]:
# Build the decision tree
tree = createTree(X, y)

# Print the constructed tree
print("Constructed Decision Tree:")
print(tree)


Constructed Decision Tree:
('n', (1, ('n', (0, ('l', 0), ('l', 1))), ('n', (0, ('l', 0), ('l', 1)))))
